<a href="https://colab.research.google.com/github/irunwazed/belajar-google-colab/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.12.0'

In [5]:
rank_0_tensor = tf.constant(4)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [6]:
rank_1_tensor = tf.constant([2,3,4,6,7])
rank_1_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 6, 7], dtype=int32)>

In [8]:
rank_2_tensor = tf.constant([[1,2],
                             [2,3],
                             [3,6]], dtype=tf.float16)
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 3.],
       [3., 6.]], dtype=float16)>

In [9]:
rank_3_tensor = tf.constant([
    [
        [1,2,3,4,6],
        [2,3,4,5,6]
    ],
    [
        [1,2,3,4,7],
        [8,9,5,3,6]
    ],
    [
        [6,5,4,2,4],
        [9,1,4,2,7]
    ]
])
rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[1, 2, 3, 4, 6],
        [2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 7],
        [8, 9, 5, 3, 6]],

       [[6, 5, 4, 2, 4],
        [9, 1, 4, 2, 7]]], dtype=int32)>

In [10]:
np.array(rank_2_tensor)

array([[1., 2.],
       [2., 3.],
       [3., 6.]], dtype=float16)